[package]
name = "lognplotgtk"
description = "Visualization tool for live data."
version = "0.1.0"
authors = ["Windel Bouwman <windel@windel.nl>"]
edition = "2018"

[dependencies]

cairo-rs = "0.8"
env_logger = "0.7.1"
gio = "0.8"
gtk = "0.8"
gdk = "0.12"
lognplot = { path = "../lognplot", features=["cairo", "server"] }
log = "0.4.8"