[package]
name = "quartzcanvas"
version = "0.1.0"
authors = ["Windel Bouwman <windel@windel.nl>"]
description = "2D Canvas abstractions"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
