
on:
  push:
    branches:
    - master

jobs:
  build_and_test:
    name: Build and test lognplot rust library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - run: cargo build
      - run: cargo test
